#!/bin/bash

release="noble"

while getopts r:p:b: flag
do
    case "${flag}" in
        r) release=${OPTARG};;
        p) ppa=${OPTARG};;
        b) package=${OPTARG};;
    esac
done

if [ -z "$package" ]; then
    echo "Enter a package name with the -b flag"
    exit 1
fi

rm -rf "dep8-${package}"

if [ -z "$ppa" ]; then
    autopkgtest -U -s -o "dep8-${package}" -B ${package} -- qemu "/var/lib/adt-images/autopkgtest-${release}-amd64.img"
else
    autopkgtest -U -s -o "dep8-${package}" --setup-commands="sudo apt install software-properties-common -y; sudo add-apt-repository -y -u -s ${ppa}" -B ${package} -- qemu "/var/lib/adt-images/autopkgtest-${release}-amd64.img"    
fi
